---
- debug:
    msg: "psql --command='\\dg' --host={{ zabbix_server_db_host|mandatory }} | grep -c zabbix"

- name: Install supporting packages
  apt:
    name: python-pip
  tags:
    - zabbix
    - configuration
    - python-packages
    - database
    - postgresql

- name: Install supporting python packages
  pip:
    name: pexpect
  tags:
    - zabbix
    - configuration
    - python-packages
    - database
    - postgresql

- name: aws postgresql | check if zabbix exists as database role in AWS RDS instance
  become: yes
  become_user: postgres
  expect:
    command: "psql --command='\\dg' --host={{ zabbix_server_db_host|mandatory }} | grep -c zabbix"
    responses:
      (?i)password: "{{ zabbix_server_db_master_pass|mandatory }}"
  register: zabbix_database_roles
  # ignore_errors: true
  tags:
    - zabbix
    - configuration
    - user
    - database
    - postgresql

- name: aws postgresql | create zabbix database role in AWS RDS instance
  become: yes
  become_user: postgres
  shell: "psql --command=\"create role zabbix with password '{{ zabbix_server_db_pass|mandatory }}' login;\" --host={{ zabbix_server_db_host|mandatory }}"
  when: zabbix_database_roles.stdout|int == 0
  tags:
    - zabbix
    - configuration
    - user
    - database
    - postgresql

- name: aws postgresql | create database in AWS RDS instance
  become: yes
  become_user: postgres
  postgresql_db:
    login_host: "{{ zabbix_server_db_host|mandatory }}"
    login_password: "{{ zabbix_server_db_master_pass|mandatory }}"
    login_user: "{{ zabbix_server_db_master_user|mandatory }}"
    name: "{{zabbix_server_db_name}}"
    owner: "{{zabbix_server_db_user}}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  register: zabbix_database_result
  tags:
    - zabbix
    - setup
    - database
    - postgresql

- name: aws postgresql | set fact
  set_fact:
    zabbix_database: "{{ zabbix_database_result|changed }}"
  tags:
    - zabbix
    - database
    - postgresql

- name: aws postgresql | stop local postgresql server
  service:
    name: postgresql
    state: stopped
  notify:
    - restart zabbix_server_or_proxy
  tags:
    - zabbix
    - database
    - postgresql
