---
- include: zabbix_server.yml

- name: Include postgresql if defined
  include: postgresql.yml
  when: "zabbix_server_db_type == 'pgsql' and zabbix_server_install == True"

- name: Include mysql if defined
  include: mysql.yml
  when: "zabbix_server_db_type == 'mysql' and zabbix_server_install == True"

- name: SSH Tunnel management for zabbix
  include: tunnel_mgt.yml
  when: "zabbix_server_tunnel == True"
