---
- name: Ensure apt zabbix.com repository exists
  apt_repository:
     repo: "deb http://repo.zabbix.com/zabbix/{{zabbix_server_major}}.{{zabbix_server_minor}}/{{ansible_distribution|lower}} {{ansible_lsb.codename}} main contrib non-free"
     state: present
  when: ansible_os_family == 'Debian'
  register: apt_repo
  tags: zabbix_server

- name : Update apt after adding repository
  apt:
     update_cache: "yes"
  when: apt_repo|changed

- name: Install Zabbix Server or Proxy
  apt:
     pkg: "zabbix-{{zabbix_server_install_type}}-{{zabbix_server_db_type}}"
     state: present
     force: yes
  when: "zabbix_server_install == True"
  tags: zabbix_server

- name: zabbix_server | Install frontend
  apt:
     pkg: "zabbix-frontend-php"
     state: present
     force: yes
  when: "zabbix_server_front_install ==  True"
  tags: zabbix_server

- name: zabbix_server | Install Zabbix agent
  apt:
     pkg: "zabbix-agent"
     state: present
     force: yes
  tags: zabbix_server

- name: zabbix_server | Ensure Zabbix agent Hostname is commented out.
  lineinfile:
    backrefs: yes
    dest: /etc/zabbix/zabbix_agentd.conf
    line: "# Hostname=\\1"
    regexp: "^Hostname=(.*)$"
  tags: zabbix_server

- name: zabbix_server | Ensure Zabbix agent HostMetadata is system.uname
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    line: "HostMetadata={{ ansible_system }}"
    insertafter: "^#\\sHostMetadata=$"
  tags: zabbix_server

- name: zabbix_server | Install pre dependency for PHP
  apt:
     pkg: "{{item}}"
     state: present
  with_items:
     - "php5-{{zabbix_server_db_type}}"
  when: "zabbix_server_front_install ==  True"
  tags: zabbix_server

- name: zabbix_server | Zabbix server conf file
  template:
     src: zabbix_server/zabbix_server.conf
     dest: /etc/zabbix/
     owner: zabbix
     group: zabbix
     mode: 0600
  when: "zabbix_server_install == True and zabbix_server_install_type == 'server'"
  tags: zabbix_server

- name: zabbix_server | Zabbix server php conf
  template:
     src: zabbix_server/zabbix.conf.php
     dest: /etc/zabbix/web
     owner: www-data
     group: www-data
     mode: 0600
  tags: zabbix_server
  when: "zabbix_server_front_install ==  True"
  notify: restart apache2

- name: zabbix_server | ensure apache2 rewrite module is present
  apache2_module:
    name: rewrite
    state: present
  tags: zabbix_server
  when: "zabbix_server_front_install ==  True"
  notify: restart apache

- name: zabbix_server | apache config
  template:
     src: apache2/apache.conf.j2
     dest: "{{zabbix_server_front_apache_conf}}"
     owner: root
     group: root
     mode: 0644
  notify: restart apache2
  when: "zabbix_server_front_install ==  True"
  tags: zabbix_server

- name: zabbix_server | Deploy html redirect
  template:
     src: zabbix_server/index.html.j2
     dest: "{{zabbix_server_front_root}}/index.html"
     owner: www-data
     group: www-data
     mode: 0644
  when: "zabbix_server_front_install ==  True and zabbix_server_front_redirect ==  True"
  notify: restart apache2

- name: Install external scripts
  get_url:
    dest: "/usr/lib/zabbix/externalscripts/{{ item.file }}"
    url: "{{ item.url }}"
    owner: zabbix
    group: zabbix
    mode: 0755
  with_items: zabbix_external_scripts|default([])
  when: "zabbix_server_install == True and zabbix_server_install_type ==  'server'"
