---

- name : zabbix_server | Update apt cache
  apt :
     update_cache="yes"

- name: zabbix_server | Install pre dependency
  apt:
     pkg="{{item}}"
     state=present
  with_items:
     - python-pip
     - libcurl3-gnutls
  tags: zabbix_server

- name: zabbix_server | Add zabbix.com repository key
  apt_key: 
     url=http://repo.zabbix.com/zabbix-official-repo.key
     state=present
  tags: zabbix_server

- name: zabbix_server | Add zabbix.com repository
  apt_repository: 
     repo='deb http://repo.zabbix.com/zabbix/{{zabbix_server_major}}.{{zabbix_server_minor}}/{{ansible_distribution|lower}} {{ansible_lsb.codename}} main contrib non-free' 
     state=present
  tags: zabbix_server

- name : zabbix_server | Update apt after adding repository
  apt :
     update_cache="yes"

- name: zabbix_server | Install Zabbix Server or proxy
  apt: 
     pkg="zabbix-{{zabbix_server_install_type}}-{{zabbix_server_db_type}}"="{{zabbix_server_ubuntu}}"
     state=present
     force=yes
  tags: zabbix_server
  when: "zabbix_server_install == True" 

- name: zabbix_server | Install frontend 
  apt: 
     pkg="zabbix-frontend-php"="{{zabbix_server_ubuntu}}"
     state=present
     force=yes
  tags: zabbix_server
  when: "zabbix_server_front_install == True" 

- name: zabbix_server | Install Zabbix agent
  apt: 
     pkg="zabbix-agent"="{{zabbix_server_ubuntu}}"
     state=present
     force=yes
  tags: zabbix_server

- name: zabbix_server | Install pre dependency for PHP
  apt:
     pkg="{{item}}"
     state=present
  with_items:
     - php5-{{zabbix_server_db_type}}
  tags: zabbix_server
  when: "zabbix_server_front_install == True" 

- name: zabbix_server | Zabbix server conf file
  template: 
     src=zabbix_server/zabbix_server.conf
     dest=/etc/zabbix/
     owner=zabbix
     group=zabbix
     mode=600
  tags: zabbix_server
  when: "zabbix_server_install == True and zabbix_server_install_type == 'server'" 

- name: zabbix_server | Zabbix server php conf 
  template:
     src=zabbix_server/zabbix.conf.php
     dest=/etc/zabbix/web
     owner=www-data
     group=www-data
     mode=600
  tags: zabbix_server  
  when: "zabbix_server_front_install == True" 
  notify: restart apache2

- name: zabbix_server | PHP timezone 
  lineinfile: 
     dest=/etc/php5/apache2/php.ini
     state=present
     regexp="date.timezone ="
     insertafter="EOF"
     line="date.timezone =  \"{{zabbix_server_timezone}}\""
     mode=0644
  notify: restart apache2
  when: "zabbix_server_front_install == True" 
  tags: zabbix_server

- name: zabbix_server | Deploy html redirect
  template: 
     src=zabbix_server/index.html.j2
     dest={{zabbix_server_front_root}}/index.html
     owner=www-data
     group=www-data
     mode=644
  when: "zabbix_server_front_install == True and zabbix_server_front_redirect == True" 
