---
- name: download .deb file
  get_url:
    dest={{ temp_dir }}/zabbix-release_2.2-1+precise_all.deb
    url=http://repo.zabbix.com/zabbix/{{zabbix_server_major}}.{{zabbix_server_minor}}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{zabbix_server_major}}.{{zabbix_server_minor}}-1+{{ansible_lsb.codename}}_all.deb
    mode=0644
  tags:
    - zabbix
    - packages

- name: install from .deb package
  command: dpkg --skip-same-version --install {{ temp_dir }}/zabbix-release_{{zabbix_server_major}}.{{zabbix_server_minor}}-1+{{ansible_lsb.codename}}_all.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  tags:
    - zabbix
    - packages

- name: refreash apt cache
  apt: update_cache=yes
  when: dpkg_result|changed
  tags:
    - zabbix
    - packages

- name: zabbix_server | Install Zabbix Server or proxy
  apt: 
     pkg="zabbix-{{zabbix_server_install_type}}-{{zabbix_server_db_type}}"="{{zabbix_server_ubuntu}}"
     state=present
     force=yes
  tags: zabbix_server
  when: "zabbix_server_install == True" 

- name: zabbix_server | Install frontend 
  apt: 
     pkg="zabbix-frontend-php"="{{zabbix_server_ubuntu}}"
     state=present
     force=yes
  tags: zabbix_server
  when: "zabbix_server_front_install == True" 

- name: zabbix_server | Install Zabbix agent
  apt: 
     pkg="zabbix-agent"="{{zabbix_server_ubuntu}}"
     state=present
     force=yes
  tags: zabbix_server

- name: zabbix_server | Install pre dependency for PHP
  apt:
     pkg="{{item}}"
     state=present
  with_items:
     - php5-{{zabbix_server_db_type}}
  tags: zabbix_server
  when: "zabbix_server_front_install == True" 

- name: zabbix_server | Zabbix server conf file
  template: 
     src=zabbix_server/zabbix_server.conf
     dest=/etc/zabbix/
     owner=zabbix
     group=zabbix
     mode=600
  tags: zabbix_server
  when: "zabbix_server_install == True and zabbix_server_install_type == 'server'" 

- name: zabbix_server | Zabbix server php conf 
  template:
     src=zabbix_server/zabbix.conf.php
     dest=/etc/zabbix/web
     owner=www-data
     group=www-data
     mode=600
  tags: zabbix_server  
  when: "zabbix_server_front_install == True" 
  notify: restart apache2

- name: zabbix_server | apache config 
  template: 
     src=apache2/apache.conf.j2
     dest="{{zabbix_server_front_apache_conf}}"
     owner=root
     group=root
     mode=0644
  notify: restart apache2
  when: "zabbix_server_front_install == True" 
  tags: zabbix_server

- name: zabbix_server | Deploy html redirect
  template: 
     src=zabbix_server/index.html.j2
     dest={{zabbix_server_front_root}}/index.html
     owner=www-data
     group=www-data
     mode=644
  when: "zabbix_server_front_install == True and zabbix_server_front_redirect == True" 
