---
- name: remote postgresql | create zabbix database user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    login_host={{ zabbix_server_db_host|mandatory }}
    encrypted=no
    name="{{zabbix_server_db_user|mandatory}}"
    password="{{zabbix_server_db_pass|mandatory}}"
  tags:
    - zabbix
    - configuration
    - user
    - database

- name: remote postgresql | create database
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    login_host={{ zabbix_server_db_host|mandatory }}
    name="{{zabbix_server_db_name|mandatory}}"
    owner="{{zabbix_server_db_user|mandatory}}"
    encoding=UTF-8
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8
    template=template0
  register: zabbix_database_result
  tags:
    - zabbix
    - setup
    - database

- name: remote postgresql | set fact
  set_fact:
    zabbix_database: "{{ zabbix_database_result|changed }}"

- name: remote postgresql | stop local postgresql server
  service:
    name=postgresql
    state=stopped
  tags:
    - zabbix
    - database

- debug: var=zabbix_database